#! /bin/sh

#Oracle Environment

PATH=$PATH:$HOME/bin

export PATH
export ORACLE_BASE=/home/oracle/app/oracle
export ORACLE_HOME=$ORACLE_BASE/product/11.2.0/db_1
export ORACLE_SID=db7node
export PATH=.:${PATH}:$HOME/bin:$ORACLE_HOME/bin
export PATH=${PATH}:/usr/bin:/bin:/usr/bin/X11:/usr/local/bin
export ORACLE_TERM=xterm
export TNS_ADMIN=$ORACLE_HOME/network/admin
export ORA_NLS33=$ORACLE_HOME/ocommon/nls/admin/data
export LD_LIBRARY_PATH=$ORACLE_HOME/lib
export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:$ORACLE_HOME/oracm/lib
export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:/lib:/usr/lib:/usr/local/lib
export CLASSPATH=$ORACLE_HOME/JRE
export CLASSPATH=${CLASSPATH}:$ORACLE_HOME/jlib
export CLASSPATH=${CLASSPATH}:$ORACLE_HOME/rdbms/jlib
export CLASSPATH=${CLASSPATH}:$ORACLE_HOME/network/jlib
export THREADS_FLAG=native
stty erase ^H
#export LANG=C
#export NLS_LANG=American_America.zhs16cgb231280
export NLS_LANG="SIMPLIFIED CHINESE_CHINA.AL32UTF8"

date=`date +'%y%m%d'`
echo $date
sqlplus $3/$4@$5<<EOF >/home/oracle/copyfrom/scripts/log/$2.log
alter session set sort_area_size = 100000000;
BEGIN DBMS_APPLICATION_INFO.SET_MODULE('MOD_$2',NULL); END;
/
alter session set NLS_DATE_FORMAT="yyyy-mm-dd hh24:mi:ss";
select sysdate begin_time from dual;
SET copytypecheck OFF
set copycommit 80
set arraysize 5000
set timing on
set lines 10000
ALTER SESSION ENABLE PARALLEL DML;
INSERT INTO EXECUTE_TOTOL_TIME(TABLE_NAME,BEGIN_TIME,END_TIME) VALUES ('$2',TO_CHAR(SYSDATE,'YYYY-MM-DD HH24:MI:SS'),NULL);
COMMIT;
@$1
commit;
UPDATE EXECUTE_TOTOL_TIME SET END_TIME = TO_CHAR(SYSDATE,'YYYY-MM-DD HH24:MI:SS') WHERE TABLE_NAME = '$2' ;
COMMIT;
select sysdate end_time from dual;
exit;
EOF
